TEST SETTINGS:
  GET_PRETRAIN: True
  TRAIN_DATE: 2023-08
  USE_PCA: True
  DATASET_PATH: E:\Workspaces\My Projects\Football-Match-Prediction\data\processed\df_GD_as_target.csv
  # Regressor: ['DecisionTreeRegressor', 'RandomForestRegressor', 'AdaBoostRegressor', 'GradientBoostingRegressor', 'XGBRegressor']
  # Classifier: ['DecisionTreeClassifier', 'RandomForestClassifier', 'AdaBoostClassifier', 'GradientBoostingClassifier', 'XGBClassifier']
  MODEL: GradientBoostingClassifier
  # Regressor: GD_Home2Away | Classifier: HomeTeam_Result
  TARGET_COL: HomeTeam_Result
TRAIN SETTINGS:
  DATE_COL: Time
  USE_PCA: False
  PLOT_MODEL_SELECTION: True
  PLOT_PCA_THRESHOLD: False
  PLOT_FEATURES_IMPORTANCE: True
  TRAIN_DATE: 2023-08
  N_TRIALS: 5
  DATASET_PATH: E:\Workspaces\My Projects\Football-Match-Prediction\data\processed\df_GD_as_target.csv
  # Regressor: ['DecisionTreeRegressor', 'RandomForestRegressor', 'AdaBoostRegressor', 'GradientBoostingRegressor', 'XGBRegressor']
  # Classifier: ['DecisionTreeClassifier', 'RandomForestClassifier', 'AdaBoostClassifier', 'GradientBoostingClassifier', 'XGBClassifier']
  MODEL: GradientBoostingClassifier
  # Regressor: GD_Home2Away | Classifier: HomeTeam_Result
  TARGET_COL: HomeTeam_Result
