TEST SETTINGS:
  AWAY_TEAM: Real Marid
  HOME_TEAM: Barcelona
TRAIN SETTINGS:
  DATE_COL: Time
  PLOT_FEATURES_IMPORTANCE: false
  TARGET_COL: GD_Home2Away
  TRAIN_DATE: 2023-08
  TRAIN_PATH: E:\Workspaces\My Projects\Football-Match-Prediction\data\processed\df_GD_as_target.csv
