GET_PRETRAIN: true
TEST SETTINGS:
  DATE_COL: Time
  USE_PCA: true
  USE_NORMALIZE: true
  PLOT_MODEL_SELECTION: false
  PLOT_PCA_THRESHOLD: false
  PLOT_FEATURES_IMPORTANCE: false
  TRAIN_DATE: 2023-08
  DATASET_PATH: D:\HUST\_Intro to DS\Capstone Project\Football-Match-Prediction\data\processed\df_GD_as_target.csv
  MODEL: DecisionTreeClassifier
  TARGET_COL: HomeTeam_Result
TRAIN SETTINGS:
  DATE_COL: Time
  USE_PCA: true
  USE_NORMALIZE: true
  PLOT_MODEL_SELECTION: false
  PLOT_PCA_THRESHOLD: false
  PLOT_FEATURES_IMPORTANCE: false
  TRAIN_DATE: 2024-08
  N_TRIALS: 10
  DATASET_PATH: D:\HUST\_Intro to DS\Capstone Project\Football-Match-Prediction\data\processed\df_GD_as_target.csv
  MODEL: DecisionTreeRegressor
  TARGET_COL: GD_Home2Away
