TEST SETTINGS:
  AWAY_TEAM: Real Marid
  HOME_TEAM: Barcelona
TRAIN SETTINGS:
  DATE_COL: Time
  USE_PCA: True
  PLOT_MODEL_SELECTION: False
  PLOT_PCA_THRESHOLD: False
  PLOT_FEATURES_IMPORTANCE: False
  TRAIN_DATE: 2024-04 # 2023-08
  N_TRIALS: 5
  DATASET_PATH: D:\HUST\_Intro to DS\Capstone Project\Football-Match-Prediction\data\processed\df_GD_as_target.csv
  # Regressor: ['DecisionTreeRegressor', 'RandomForestRegressor', 'AdaBoostRegressor', 'GradientBoostingRegressor', 'XGBRegressor']
  # Classifier: ['DecisionTreeClassifier', 'RandomForestClassifier', 'AdaBoostClassifier', 'GradientBoostingClassifier', 'XGBClassifier']
  MODEL: RandomForestRegressor
  # Regressor: GD_Home2Away | Classifier: HomeTeam_Result
  TARGET_COL: GD_Home2Away
